spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Iv1.33f916bf11fa15cc
            clientSecret: 4034d433924e3a83c660ed1e6d3e2c4f77572ba3
          google:
            clientId: 82356675402-ts46qj94fb7fqf7iheqrl68i4h4967ke.apps.googleusercontent.com
            clientSecret: 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

